msi_admin_dashboard:
    pattern: /admin/
    defaults: { _controller: MsiAdminBundle:Dashboard:dashboard }

msi_admin_limit:
    pattern: /change-limit
    defaults: { _controller: MsiAdminBundle:Default:limit }

msi_admin_working_locale:
    pattern: /change-working-locale
    defaults: { _controller: MsiAdminBundle:Default:workingLocale }

msi_page_show:
    pattern: /{_locale}/{slug}
    defaults: { _controller: MsiAdminBundle:Page:show, slug: ~ }
    requirements:
        _locale: fr|en

tinymce_login:
    pattern: /_tinymce/login
    defaults: { _controller: MsiAdminBundle:Default:tinymcelogin }

msi_admin_menu_node_admin_sort:
    pattern: /admin/menu-node/sort.html
    defaults: { _controller: MsiAdminBundle:Admin/MenuNode:sort, _admin: msi_admin_menu_node_admin }
